### ISSUE TITLE
Not a issue, but a question about your project (comparating it to another solution)

### ISSUE THREAD

**Issue by regnou** [tylim88/FirelordJS#76]
Hi,
Here is quick hack to have types with firebase:
https://javascript.plainenglish.io/using-firestore-with-typescript-in-the-v9-sdk-cf36851bb099
https://github.com/JamieCurnow/firebase-v9-typescript-example

Could you tell me, very shortly, what does your library FirelordJS offers more ? Because, well, I am pretty sure I did something wrong, but I was trying your lib with sveltekit and ts. And I have encountered issues (unfortunately, I dont remember exactly what it was...), and at the end, comparated to the little hack mentioned above, I hesitate to use your lib, because first, I will depends on a non official lib, FirelordJS, instead the official one Firebase-firestore... And then, I have heard that it is not easy to SSR transform the firestore sdk code in sveltekit... so using your lib could also be more difficult...

That is why, I am mitigated to use your lib, could you argue something to help to do the good decision ? 
Tks

**Comment by tylim88** [comment]
> And I have encountered issues (unfortunately, I dont remember exactly what it was...), and at the end, comparated to the little hack mentioned above, 

most likely you violated the type-safety mechanic, the type checking of FirelorsJS is very strict(like really really strict) and you will encounter a lot of type error (that is the purpose of this library: extreme type safety)

it may also be caused by a bug

I need to know what error you faced, what operation you run and your Meta Type in order to help you with it

> I hesitate to use your lib, because first, I will depends on a non official lib, FirelordJS, instead the official one Firebase-firestore

there are some differences where you can skip some parameters but overall it shares almost the same documentation with the official SDK

> And then, I have heard that it is not easy to SSR transform the firestore sdk code in sveltekit... so using your lib could also be more difficult...

I am not a svelte user, so I don't sure what this means. 

One thing for sure is, if my library cannot run in SSR, neither can the official SDK, majority of FirelordJS codes are type definitions, and the rest is a thin wrapper over the original SDK runtime code.

And I'm pretty sure the official SDK can run in Nodejs environment, even though it is a client SDK. I am not sure how is Svelte SSR different from typical nodejs environment but common sense tells me it shouldn't be a problem.

==============

long thing short, the library focus on type safety, any possible loophole in term of type safety, is taken care of by this library

this includes type-safe loophole that people don't usually think of

not that they don't stumble upon such loophole, but when they stumble upon it, they solve it with a more "primitive" approach

for example, below is [Firestore Query Limitations](https://firebase.google.com/docs/firestore/query-data/queries?hl=en&authuser=0)

![image](https://user-images.githubusercontent.com/5227509/187742464-851952e2-13a0-4525-9918-a42c25d6e8a9.png)

let so you write something like this:

`query(ref, where('a', 'not-in', ['1']), where('b', '!=', true))`, so obviously you violated this rule: **You can't combine not-in with not equals !=.**

so what is a primitive approach to solving this?

easy, you run your tests, see if there is runtime error or not and if there is, you fix it

but you only catch it if you indeed include it in your tests, else it will hit production.

FirelordJS checks for errors like this, the second you type your code, Typescript immediately check whether you break the query rules or not

This is known as rule typing, and there is no wrapper out there capable of offering this level of type safety

example other mechanic is (type conversion)[https://firelordjs.com/type_conversion], like the read type and write type are different, for example if your data type is number, then you can write increment or number to it, but only read it as number.

also, some runtime utilities that stops (implicit updateDoc data deletion behaviour )[https://firelordjs.com/highlights/update#dangerous-firestore-sdk-update-api-]

(Inhomogeneous field value)[https://firelordjs.com/highlights/inhomogeneous_field_values], so you don't mix up your field value

and a lot of other type safe mechanics that I couldn't even able to remember all of them myself

I recommend you slowly go through the documentation of what this library can do.

so to answer your question

> Hi,
> Here is quick hack to have types with firebase:
> https://javascript.plainenglish.io/using-firestore-with-typescript-in-the-v9-sdk-cf36851bb099
> https://github.com/JamieCurnow/firebase-v9-typescript-example
> 
> Could you tell me, very shortly, what does your library FirelordJS offers more ? 

more than you could ever imagine

**Comment by tylim88** [comment]
Also some back story, Jamie's post is what inspired me to write FirelordJS, you can even find my comment under one of his posts.

I was looking for type-safe method to write Firestore code, but I quickly reached the limit and needed something truly powerful
