### ISSUE TITLE
Meta Type with union base type

### ISSUE THREAD

**Issue by focafull** [tylim88/FirelordJS#80]
Hi,
first of all, this library is really nice to work with and it has helped me a lot. Now to my problem.
I try to create a Meta Type that can be of two different base types that have some properties in common, here my Base Types with Meta Type:

```typescript
export type ShoppingListItemType = MetaTypeCreator<{
  name: string, // GeneralItem
  quantity: string,
  checked: boolean,
  discounts: Discount[],
} | {
  name: string,  // SpecialItem
  quantity: string,
  checked: boolean,
  category: string,
  discount: Discount | PossiblyReadAsUndefined,
  added: Date | Timestamp | FieldValue,
}, 'items', string, ShoppingListsType>
```

Then when I want to create a document like this.
```typescript
const ref = getFirelord<ShoppingListItemType>()(`users/${uid}/shoppingLists/${shoppingListId}/items`).doc(itemId.toString());

await setDoc(ref, item); // Error at item
```
When I use auto completion to check which properties are available, it shows me only name, quantity and checked.

Here you can see the error I'm getting:
```
Argument of type 'ShoppingListItem' is not assignable to parameter of type 'HandleUnknownMember<{ name: string; quantity: string; checked: boolean; }, GeneralItem> | HandleUnknownMember<{ name: string; quantity: string; checked: boolean; }, SpecialItem>'.
  Type 'GeneralItem' is not assignable to type 'HandleUnknownMember<{ name: string; quantity: string; checked: boolean; }, GeneralItem> | HandleUnknownMember<{ name: string; quantity: string; checked: boolean; }, SpecialItem>'.
    Type 'GeneralItem' is not assignable to type 'HandleUnknownMember<{ name: string; quantity: string; checked: boolean; }, GeneralItem>'.
      Type 'GeneralItem' is not assignable to type '{ discounts: "Error: Please remove the unknown member ( discounts )"; }'.
        Types of property 'discounts' are incompatible.
          Type 'Discount[]' is not assignable to type '"Error: Please remove the unknown member ( discounts )"'.ts(2345)
```

I will be thankfull for any help.

**Comment by tylim88** [comment]
FirelordJS does not support object union although it is technically possible
![image](https://user-images.githubusercontent.com/5227509/189561078-49c4913d-06aa-41f4-b568-63c5b0917948.png)
[limitations](https://firelordjs.com/limitation)

we usually don't expect a document to have 2 data types, just like we don't have 2 schemas for a SQL database table

I can understand that given noSQL flexibility, multiple schemas per document is something conceptually valid

you can do something like this:
```ts
export type ShoppingListItemType = MetaTypeCreator<{
  name: string, // GeneralItem
  quantity: string,
  checked: boolean,
  discounts: Discount[],
  discount: Discount | PossiblyReadAsUndefined,
  added: Date | Timestamp | ServerTimestamp | PossiblyReadAsUndefined,
}, 'items', string, ShoppingListsType>
```
this is a good enough solution but is not a perfect solution compared to the union one because we want to expect `added` is not possibly undefined if `discount` exists. But in this solution, both are possibly undefined

Enabling object union is possible but I need more justification, I need to change a lot of code and add many tests to make it possible.

Also please don't use FieldValue, use ServerTimestamp instead, it is more [granular](https://firelordjs.com/highlights/inhomogeneous_field_values/).

I think you also using a very old version because I no longer export `FieldValue`(let me know if you have problem updating it)

**Comment by focafull** [comment]
Thanks a lot for the quick answer, I will probably resolve to merging those two types, so I only have to deal with one type.
