### ISSUE TITLE
[ENHANCEMENT] Abstract MetaType

### ISSUE THREAD

**Issue by ArStah** [tylim88/FirelordJS#90]
Hello again. After resolving issue https://github.com/tylim88/FirelordJS/issues/89 I've got another one)

All collections in my Firestore have few required fields, that have same types, so it would be great to have some kind of AbstractMetaType, where I can put those fields, and then extend that type by the specific MetaType for the specific collection. 
It will be useful again in those helper functions, described in https://github.com/tylim88/FirelordJS/issues/89, because for now they are stick to specific MetaType, so when I want to use that function to update document from another collection, i have to change `$firestoreUpdate` helper's signature, which looks inconvenient. 

Here is an approximate example for what do i mean:

```typescript
export type FirestoreEntityData = {
  _uid: string;
  // STATUS
  status: EntityStatus;
  //
  update_action: UpdateAction;
  // TIMESTAMPS
  created_at: ServerTimestamp;
  creator_uuid: string;
  created_by_platform: string;
  //
  updated_at: ServerTimestamp;
  updated_by_uuid: string;
  updated_by_platform: string;
  //
  deleted_at: ServerTimestamp | null;
  deleted_by_uuid: string | null;
  deleted_by_platform: string | null;
};

export type AbstractEntityMetaType = AbstractMetaTypeCreator<FirestoreEntityData>; // No collection name, id type and parent

// Then creating specific MetaType

export type FirestoreChatData = {
  name: string;
};

export type ChatMetaType = MetaTypeCreatorFromAbstract<AbstractEntityMetaType, FirestoreChatData, 'Chats'>;

export type FirestoreUserData = {
  first_name: string;
  last_name: string;
};

export type UserMetaType = MetaTypeCreatorFromAbstract<AbstractEntityMetaType, FirestoreUserData, 'Users'>;
```
This extension may be done just by making 
```typescript
export type FirestoreChatData = {
  name: string;
} & FirestoreEntityData;
```
But main idea is to make `AbstractEntityMetaType` compatible with any other `MetaType`, extended from it, when working with only fields, that are present in `FirestoreEntityData`

So then we can use it like this:

```typescript
const timestamp = serverTimestamp();

type FirestoreUpdateParams<
  T extends AbstractEntityMetaType,
  K extends Partial<T['write']>
> = {
  batch?: WriteBatch;
  ref: DocumentReference<T>;
  data: K;
  action: string;
  params?: DocumentData;
};

export function $firestoreUpdate<
  T extends AbstractEntityMetaType,
  K extends Partial<T['write']>,
>({
  batch,
  ref,
  data,
  action,
  params = {},
}: FirestoreUpdateParams<T, K>): Promise<void> {
  const mixin: K = {
    update_action: {
      type: action,
      params,
      timestamp,
    },
    updated_by_uuid: store.getters['auth/user'].uid,
    updated_at: timestamp,
    updated_by_platform: 'web' ,
  };

  const mixedData = {
    ...data,
    ...mixin,
  };

  if (batch) {
    batch.update(ref, mixedData);
    return Promise.resolve();
  }

  // No error, since all props, added in mixin are present in AbstractEntityType['Write']
  return updateDoc(ref, mixedData);
}

// And usage

$firestoreUpdate({
  ref: ChatRef,
  data: { name: 'Test' },
});
//
$firestoreUpdate({
  ref: UserRef,
  data: {  first_name: 'Vasya Pupkin' },
});
``` 

Maybe it's already possible, and I'm missing something. 
Also I'm quite new to typescript, so maybe have some mistakes in my assumptions

**Comment by tylim88** [comment]
Usually abstraction is not library's responsibility, we don't see library provide tools to make abstraction easy, at least it is never a priority

However advance type library is not a common library, I decided to add some utility types from time to time to help those who want to hold tight to DRY principle

```ts
import {
	MetaTypeCreator,
	WriteBatch,
	DocumentReference,
	AbstractMetaTypeCreator,
	updateDoc,
} from 'firelordjs'

type A = { a: number }
type AbstractMetaType = AbstractMetaTypeCreator<A>
type AB = MetaTypeCreator<A & { b: string }, 'AB'>
type AC = MetaTypeCreator<A & { c: boolean }, 'AC'>

type FirestoreUpdateParams<T extends AbstractMetaType> = {
	batch?: WriteBatch
	ref: DocumentReference<T>
	data: Partial<T['writeFlatten']>
}

export function $firestoreUpdate<T extends AbstractMetaType>({
	batch,
	ref,
	data,
}: FirestoreUpdateParams<T>): Promise<void> {
	const mixin = {
		a: 123,
	}

	const mixedData: Partial<T['write']> = {
		...data,
		...mixin,
	}

	if (batch) {
		batch.update(
			ref,
			//@ts-expect-error
			mixedData
		)
		return Promise.resolve()
	}

	return updateDoc(
		ref,
		//@ts-expect-error
		mixedData
	)
}

const b = 1 as unknown as DocumentReference<AB>
const c = 1 as unknown as DocumentReference<AC>

$firestoreUpdate({
	ref: b,
	data: { b: 'Test' },
})
//
$firestoreUpdate({
	ref: c,
	data: { c: false },
})
```
`AbstractMetaTypeCreator` will be available in v2.2.1

do note that you need to suppress 2 type errors with `//@ts-expect-error` or type cast it, in this example, I use `//@ts-expect-error` 

This is needed because now you are relying on generic type, and the conditional type is not able to resolve: the moment you supply `mixedData` to `update`, TS does not know what the generic type will be, hence the conditional type remain as the conditional type 
![image](https://user-images.githubusercontent.com/5227509/215195327-6e7a428a-2226-404a-b283-ed188ed32e60.png)

Error like this is very common if you try to abstract on any library with advance typing because those library usually utilize a lot of conditional types

So the question is, is this safe? 

The moment we suppress the error with `ts-expect-error` or type cast, it is no longer safe in strict sense

However it is still safe in practice as long as you do not mess up the type of your `data`

It does comes with cost,, it requires better understanding of how Typescript and Firelord works, which mean reduction in user experience

**Comment by tylim88** [comment]
v2.2.1 is now available: https://github.com/tylim88/FirelordJS/releases/tag/2.2.1

**Comment by ArStah** [comment]
Wow, thanks for quick response and solution!

**Comment by tylim88** [comment]
updated my answer
