### ISSUE TITLE
Node module resolution issue

### ISSUE THREAD

**Issue by budokans** [tylim88/FirelordJS#95]
Hi there! Thanks for the excellent library.

It's not a _must-have_, but it would be cool if you could build with target set to CommonJS, as users of frameworks like Nextjs (<v13) will run into Nodejs module resolution issues. It can be solved with `next-transpile-modules`, but it can take some time to unearth that solution - I almost gave up.

Thanks again,
Steven

**Comment by tylim88** [comment]
the target was commonJS, but after firebase updated to v9.17.1, the `require` import from `firestore lite` instead of `firestore` and this library [became unuse able](https://github.com/tylim88/FirelordJS/issues/91#issuecomment-1421219149)

I think I will keep thing as it is now, until we have similar issue again

anyway, thanks for using Firelord!

**Comment by TomKaltz** [comment]
So what is the remedy here?  I am running with 'commonjs' for a Quasar/Vue3 project and I'm getting ```Cannot find module 'firelordjs' or its corresponding type declarations.ts(2307)``` when trying to import the library.
